### ISSUE TITLE
Submit Paper [Preliminary]

### ISSUE THREAD

**Issue by jbae11** [arfc/2018-bae-benchmark#15]
This paper now has the zenodo reference (a1d14f2ea993cff329fa9a83f8bd75cf1c4a8882) and is ready for submission. 

The plan is to change the zenodo after the [Cycamore::Reactor change](https://github.com/cyclus/cycamore/pull/489) is reflected in the input files in the [transition-scenarios repo](github.com/arfc/transition-scenarios) after the initial submission.

**Comment by katyhuff** [comment]
@jbae11 -- sent you an email about final approval - still waiting on response - did you get the email?

**Comment by jbae11** [comment]
I just found it, it looks good! I think there's a comma missing after 'DYMOND' in the abstract.
I also just fixed the conflict.

**Comment by katyhuff** [comment]
fixed dymond comma issue. Thanks for handling the conflict. I'll fix the abstract in the metadata, reupload the new pdfs according to the changes in a1d14f2 and will submit!! 
Will close this when complete.

**Comment by katyhuff** [comment]
All done! You should receive an email from annals. Let me know if you don't. Congratulations and thank you for doing so much great work toward this!
