### ISSUE TITLE
Comments and suggestions - gwen 

### ISSUE THREAD

**Issue by gwenchee** [arfc/2018-bae-benchmark#9]
Overall comments:
1) You should be more consistent with referring to the original benchmark and your new one. You bounce between verification study and benchmark and previous benchmark. 
2) You should pick a tense for referring to your study, I changed what i could to past tense. 
3) I think you might have overused "note". 

Attachment with some comments: 
[2018-bae-benchmark-gwenedits.pdf](https://github.com/arfc/2018-bae-benchmark/files/2285290/2018-bae-benchmark-gwenedits.pdf)

**Comment by jbae11** [comment]
@gwenchee  Thank you so much! I pushed the edited files!
